### PR TITLE
Fix/question unit api

### LINKED ISSUE #137: NODE - Update Unit and Question APIs
Update Question and Unit APIs with reference to the changes in their models.
Some to note might be:

- [ ] Changes in fields to be accepted
[Database Design Reference](https://docs.google.com/spreadsheets/d/1lUj5XLwv89rzNixoq-NBfGRep3ZfR4faLniPbmiImHc/edit#gid=1938297510)

- [ ] Make sure all endpoints are functional again
[Routing reference](https://docs.google.com/spreadsheets/d/1ESuvWDwBRUpHYf27nYEIhZO7znjFie7usxnZeOl_E1s/edit#gid=892754388) 

For later
- Validation if question's learn_type matches unit's unit_type
- Validate inputted content_ids if it exists

### PR DESCRIPTION
**Pull request by sbenemerito**
Closes #137

### CODE REVIEW

File: backend_node/controllers/question.controller.js [hunk 1]
```diff
@@ -39,67 +38,73 @@ exports.findOne = (req, res) => {
...
-    )
+  }
+
+  Question.findOne({
+    where: {
+      id: req.params.id,
+      is_active: true
+    }
+  })
     .then(question => {
```
Comment (hugh-n) [inline backend_node/controllers/question.controller.js]: Remove two spaces here. Make indentation more consistent.

File: backend_node/controllers/question.controller.js [hunk 2]
```diff
@@ -39,67 +38,73 @@ exports.findOne = (req, res) => {
...
-          msg: modelName + " not found!"
+          msg: "No question with this ID found!"
         });
       }
+
+      question.update({
+        unit_id: req.body.unit_id,
+        content_ids: req.body.content_ids
+      })
+        .then(question => {
```
Comment (hugh-n) [inline backend_node/controllers/question.controller.js]: Same here

File: backend_node/controllers/question.controller.js [hunk 3]
```diff
@@ -108,60 +113,37 @@ exports.update = (req, res) => {
...
-      {
-        transaction: t
-      }
-    )
+  Question.findOne({
+    where: {
+      id: req.params.id
+    }
+  })
     .then(question => {
```
Comment (hugh-n) [inline backend_node/controllers/question.controller.js]: Same here.

File: backend_node/controllers/question.controller.js [hunk 4]
```diff
@@ -108,60 +113,37 @@ exports.update = (req, res) => {
...
+        res.status(404).json({
+          success: false,
+          msg: "No question with this ID found!"
+        });
+      }
+
+      question.update({
+          is_active: !question.is_active
+      })
         .then(question => {
```
Comment (hugh-n) [inline backend_node/controllers/question.controller.js]: Same here.

File: backend_node/controllers/unit.controller.js [hunk 5]
```diff
@@ -55,7 +54,7 @@ exports.create = (req, res) => {
       title: req.body.title,
       schedule: req.body.schedule,
       unit_type: req.body.unit_type,
-      assignments_id: req.body.assignments_id,
+      assignments_id: req.body.assignments_id
     })
       .then((unit) => {
```
Comment (hugh-n) [inline backend_node/controllers/unit.controller.js]: Also here.

File: backend_node/controllers/unit.controller.js [hunk 6]
```diff
@@ -71,42 +70,49 @@ exports.create = (req, res) => {
...
         });
       }
+
+      unit.update({
+        title: req.body.title,
+        schedule: req.body.schedule,
+        unit_type: req.body.unit_type,
+        assignments_id: req.body.assignments_id
+      })
+        .then(unit => {
```
Comment (hugh-n) [inline backend_node/controllers/unit.controller.js]: Here also.

File: backend_node/controllers/unit.controller.js [hunk 7]
```diff
@@ -115,69 +121,45 @@ exports.update = (req, res) => {
...
-      })
-      .catch(err => {
-        console.log(err);
-        res.status(500).json({
+  Unit.findOne({
+    where: {
+      id: req.params.id
+    }
+  })
+    .then(unit => {
```
Comment (hugh-n) [inline backend_node/controllers/unit.controller.js]: Decrease indentation by two spaces in here also.

File: backend_node/controllers/unit.controller.js [hunk 8]
```diff
@@ -115,69 +121,45 @@ exports.update = (req, res) => {
...
           success: false,
-          msg: "Something went wrong: " + err
+          msg: "No unit with this ID found!"
         });
+      }
+
+      unit.update({
+          is_active: !unit.is_active
+      })
+        .then(question => {
```
Comment (hugh-n) [inline backend_node/controllers/unit.controller.js]: And here as well.

File: backend_node/controllers/unit.controller.js [hunk 9]
```diff
@@ -39,7 +41,58 @@ exports.findOne = (req, res) => {
...
+      model: Question,
+      as: 'questions',
+      where: {
+        unit_id: req.params.id,
+        is_active: true
+      },
+      required: false,
+    }]
+  })
+    .then(unit => {
```
Comment (hugh-n) [inline backend_node/controllers/unit.controller.js]: Remove two spaces in indentation here.
